from src.models.security_master import SecurityMasterRecord

COMMON_US_STOCKS: list[SecurityMasterRecord] = [
    SecurityMasterRecord(symbol="AAPL", name="Apple Inc.", asset_type="stock", exchange="NASDAQ", sector="Technology"),
    SecurityMasterRecord(symbol="MSFT", name="Microsoft Corporation", asset_type="stock", exchange="NASDAQ", sector="Technology"),
    SecurityMasterRecord(symbol="GOOGL", name="Alphabet Inc. Class A", asset_type="stock", exchange="NASDAQ", sector="Technology"),
    SecurityMasterRecord(symbol="AMZN", name="Amazon.com Inc.", asset_type="stock", exchange="NASDAQ", sector="Consumer Cyclical"),
    SecurityMasterRecord(symbol="NVDA", name="NVIDIA Corporation", asset_type="stock", exchange="NASDAQ", sector="Technology"),
    SecurityMasterRecord(symbol="META", name="Meta Platforms Inc.", asset_type="stock", exchange="NASDAQ", sector="Technology"),
    SecurityMasterRecord(symbol="TSLA", name="Tesla Inc.", asset_type="stock", exchange="NASDAQ", sector="Consumer Cyclical"),
    SecurityMasterRecord(symbol="BRK.B", name="Berkshire Hathaway Inc. Class B", asset_type="stock", exchange="NYSE", sector="Financial Services"),
    SecurityMasterRecord(symbol="JPM", name="JPMorgan Chase & Co.", asset_type="stock", exchange="NYSE", sector="Financial Services"),
    SecurityMasterRecord(symbol="JNJ", name="Johnson & Johnson", asset_type="stock", exchange="NYSE", sector="Healthcare"),
    SecurityMasterRecord(symbol="V", name="Visa Inc.", asset_type="stock", exchange="NYSE", sector="Financial Services"),
    SecurityMasterRecord(symbol="UNH", name="UnitedHealth Group Inc.", asset_type="stock", exchange="NYSE", sector="Healthcare"),
    SecurityMasterRecord(symbol="HD", name="The Home Depot Inc.", asset_type="stock", exchange="NYSE", sector="Consumer Cyclical"),
    SecurityMasterRecord(symbol="PG", name="Procter & Gamble Co.", asset_type="stock", exchange="NYSE", sector="Consumer Defensive"),
    SecurityMasterRecord(symbol="MA", name="Mastercard Inc.", asset_type="stock", exchange="NYSE", sector="Financial Services"),
    SecurityMasterRecord(symbol="XOM", name="Exxon Mobil Corporation", asset_type="stock", exchange="NYSE", sector="Energy"),
    SecurityMasterRecord(symbol="LLY", name="Eli Lilly and Company", asset_type="stock", exchange="NYSE", sector="Healthcare"),
    SecurityMasterRecord(symbol="ABBV", name="AbbVie Inc.", asset_type="stock", exchange="NYSE", sector="Healthcare"),
    SecurityMasterRecord(symbol="MRK", name="Merck & Co. Inc.", asset_type="stock", exchange="NYSE", sector="Healthcare"),
    SecurityMasterRecord(symbol="AVGO", name="Broadcom Inc.", asset_type="stock", exchange="NASDAQ", sector="Technology"),
    SecurityMasterRecord(symbol="PEP", name="PepsiCo Inc.", asset_type="stock", exchange="NASDAQ", sector="Consumer Defensive"),
    SecurityMasterRecord(symbol="KO", name="The Coca-Cola Company", asset_type="stock", exchange="NYSE", sector="Consumer Defensive"),
    SecurityMasterRecord(symbol="COST", name="Costco Wholesale Corporation", asset_type="stock", exchange="NASDAQ", sector="Consumer Defensive"),
    SecurityMasterRecord(symbol="TMO", name="Thermo Fisher Scientific Inc.", asset_type="stock", exchange="NYSE", sector="Healthcare"),
    SecurityMasterRecord(symbol="WMT", name="Walmart Inc.", asset_type="stock", exchange="NYSE", sector="Consumer Defensive"),
    SecurityMasterRecord(symbol="CSCO", name="Cisco Systems Inc.", asset_type="stock", exchange="NASDAQ", sector="Technology"),
    SecurityMasterRecord(symbol="CRM", name="Salesforce Inc.", asset_type="stock", exchange="NYSE", sector="Technology"),
    SecurityMasterRecord(symbol="ACN", name="Accenture plc", asset_type="stock", exchange="NYSE", sector="Technology"),
    SecurityMasterRecord(symbol="MCD", name="McDonald's Corporation", asset_type="stock", exchange="NYSE", sector="Consumer Cyclical"),
    SecurityMasterRecord(symbol="ABT", name="Abbott Laboratories", asset_type="stock", exchange="NYSE", sector="Healthcare"),
    SecurityMasterRecord(symbol="DHR", name="Danaher Corporation", asset_type="stock", exchange="NYSE", sector="Healthcare"),
    SecurityMasterRecord(symbol="NFLX", name="Netflix Inc.", asset_type="stock", exchange="NASDAQ", sector="Communication Services"),
    SecurityMasterRecord(symbol="AMD", name="Advanced Micro Devices Inc.", asset_type="stock", exchange="NASDAQ", sector="Technology"),
    SecurityMasterRecord(symbol="INTC", name="Intel Corporation", asset_type="stock", exchange="NASDAQ", sector="Technology"),
    SecurityMasterRecord(symbol="DIS", name="The Walt Disney Company", asset_type="stock", exchange="NYSE", sector="Communication Services"),
    SecurityMasterRecord(symbol="ADBE", name="Adobe Inc.", asset_type="stock", exchange="NASDAQ", sector="Technology"),
    SecurityMasterRecord(symbol="TXN", name="Texas Instruments Inc.", asset_type="stock", exchange="NASDAQ", sector="Technology"),
    SecurityMasterRecord(symbol="PM", name="Philip Morris International Inc.", asset_type="stock", exchange="NYSE", sector="Consumer Defensive"),
    SecurityMasterRecord(symbol="NEE", name="NextEra Energy Inc.", asset_type="stock", exchange="NYSE", sector="Utilities"),
    SecurityMasterRecord(symbol="RTX", name="RTX Corporation", asset_type="stock", exchange="NYSE", sector="Industrials"),
    SecurityMasterRecord(symbol="QCOM", name="Qualcomm Inc.", asset_type="stock", exchange="NASDAQ", sector="Technology"),
    SecurityMasterRecord(symbol="LOW", name="Lowe's Companies Inc.", asset_type="stock", exchange="NYSE", sector="Consumer Cyclical"),
    SecurityMasterRecord(symbol="UPS", name="United Parcel Service Inc.", asset_type="stock", exchange="NYSE", sector="Industrials"),
    SecurityMasterRecord(symbol="BA", name="The Boeing Company", asset_type="stock", exchange="NYSE", sector="Industrials"),
    SecurityMasterRecord(symbol="CAT", name="Caterpillar Inc.", asset_type="stock", exchange="NYSE", sector="Industrials"),
    SecurityMasterRecord(symbol="GS", name="The Goldman Sachs Group Inc.", asset_type="stock", exchange="NYSE", sector="Financial Services"),
    SecurityMasterRecord(symbol="AMGN", name="Amgen Inc.", asset_type="stock", exchange="NASDAQ", sector="Healthcare"),
    SecurityMasterRecord(symbol="ISRG", name="Intuitive Surgical Inc.", asset_type="stock", exchange="NASDAQ", sector="Healthcare"),
    SecurityMasterRecord(symbol="SBUX", name="Starbucks Corporation", asset_type="stock", exchange="NASDAQ", sector="Consumer Cyclical"),
    SecurityMasterRecord(symbol="GILD", name="Gilead Sciences Inc.", asset_type="stock", exchange="NASDAQ", sector="Healthcare"),
    SecurityMasterRecord(symbol="BLK", name="BlackRock Inc.", asset_type="stock", exchange="NYSE", sector="Financial Services"),
    SecurityMasterRecord(symbol="SYK", name="Stryker Corporation", asset_type="stock", exchange="NYSE", sector="Healthcare"),
    SecurityMasterRecord(symbol="AXP", name="American Express Company", asset_type="stock", exchange="NYSE", sector="Financial Services"),
    SecurityMasterRecord(symbol="MDLZ", name="Mondelez International Inc.", asset_type="stock", exchange="NASDAQ", sector="Consumer Defensive"),
    SecurityMasterRecord(symbol="SPGI", name="S&P Global Inc.", asset_type="stock", exchange="NYSE", sector="Financial Services"),
    SecurityMasterRecord(symbol="DE", name="Deere & Company", asset_type="stock", exchange="NYSE", sector="Industrials"),
    SecurityMasterRecord(symbol="CVX", name="Chevron Corporation", asset_type="stock", exchange="NYSE", sector="Energy"),
    SecurityMasterRecord(symbol="PYPL", name="PayPal Holdings Inc.", asset_type="stock", exchange="NASDAQ", sector="Financial Services"),
    SecurityMasterRecord(symbol="SQ", name="Block Inc.", asset_type="stock", exchange="NYSE", sector="Technology"),
    SecurityMasterRecord(symbol="SNAP", name="Snap Inc.", asset_type="stock", exchange="NYSE", sector="Communication Services"),
    SecurityMasterRecord(symbol="UBER", name="Uber Technologies Inc.", asset_type="stock", exchange="NYSE", sector="Technology"),
    SecurityMasterRecord(symbol="ABNB", name="Airbnb Inc.", asset_type="stock", exchange="NASDAQ", sector="Consumer Cyclical"),
    SecurityMasterRecord(symbol="PLTR", name="Palantir Technologies Inc.", asset_type="stock", exchange="NYSE", sector="Technology"),
    SecurityMasterRecord(symbol="RIVN", name="Rivian Automotive Inc.", asset_type="stock", exchange="NASDAQ", sector="Consumer Cyclical"),
    SecurityMasterRecord(symbol="COIN", name="Coinbase Global Inc.", asset_type="stock", exchange="NASDAQ", sector="Financial Services"),
    SecurityMasterRecord(symbol="SHOP", name="Shopify Inc.", asset_type="stock", exchange="NYSE", sector="Technology"),
    SecurityMasterRecord(symbol="SNOW", name="Snowflake Inc.", asset_type="stock", exchange="NYSE", sector="Technology"),
    SecurityMasterRecord(symbol="NET", name="Cloudflare Inc.", asset_type="stock", exchange="NYSE", sector="Technology"),
    SecurityMasterRecord(symbol="CRWD", name="CrowdStrike Holdings Inc.", asset_type="stock", exchange="NASDAQ", sector="Technology"),
    SecurityMasterRecord(symbol="DDOG", name="Datadog Inc.", asset_type="stock", exchange="NASDAQ", sector="Technology"),
    SecurityMasterRecord(symbol="ZS", name="Zscaler Inc.", asset_type="stock", exchange="NASDAQ", sector="Technology"),
    SecurityMasterRecord(symbol="PANW", name="Palo Alto Networks Inc.", asset_type="stock", exchange="NASDAQ", sector="Technology"),
    SecurityMasterRecord(symbol="NOW", name="ServiceNow Inc.", asset_type="stock", exchange="NYSE", sector="Technology"),
    SecurityMasterRecord(symbol="ENPH", name="Enphase Energy Inc.", asset_type="stock", exchange="NASDAQ", sector="Technology"),
    SecurityMasterRecord(symbol="F", name="Ford Motor Company", asset_type="stock", exchange="NYSE", sector="Consumer Cyclical"),
    SecurityMasterRecord(symbol="GM", name="General Motors Company", asset_type="stock", exchange="NYSE", sector="Consumer Cyclical"),
    SecurityMasterRecord(symbol="T", name="AT&T Inc.", asset_type="stock", exchange="NYSE", sector="Communication Services"),
    SecurityMasterRecord(symbol="VZ", name="Verizon Communications Inc.", asset_type="stock", exchange="NYSE", sector="Communication Services"),
    SecurityMasterRecord(symbol="PFE", name="Pfizer Inc.", asset_type="stock", exchange="NYSE", sector="Healthcare"),
    SecurityMasterRecord(symbol="BMY", name="Bristol-Myers Squibb Company", asset_type="stock", exchange="NYSE", sector="Healthcare"),
    SecurityMasterRecord(symbol="C", name="Citigroup Inc.", asset_type="stock", exchange="NYSE", sector="Financial Services"),
    SecurityMasterRecord(symbol="BAC", name="Bank of America Corporation", asset_type="stock", exchange="NYSE", sector="Financial Services"),
    SecurityMasterRecord(symbol="WFC", name="Wells Fargo & Company", asset_type="stock", exchange="NYSE", sector="Financial Services"),
    SecurityMasterRecord(symbol="MS", name="Morgan Stanley", asset_type="stock", exchange="NYSE", sector="Financial Services"),
    SecurityMasterRecord(symbol="SCHW", name="Charles Schwab Corporation", asset_type="stock", exchange="NYSE", sector="Financial Services"),
    SecurityMasterRecord(symbol="COP", name="ConocoPhillips", asset_type="stock", exchange="NYSE", sector="Energy"),
    SecurityMasterRecord(symbol="SLB", name="Schlumberger Limited", asset_type="stock", exchange="NYSE", sector="Energy"),
    SecurityMasterRecord(symbol="AMAT", name="Applied Materials Inc.", asset_type="stock", exchange="NASDAQ", sector="Technology"),
    SecurityMasterRecord(symbol="LRCX", name="Lam Research Corporation", asset_type="stock", exchange="NASDAQ", sector="Technology"),
    SecurityMasterRecord(symbol="MU", name="Micron Technology Inc.", asset_type="stock", exchange="NASDAQ", sector="Technology"),
    SecurityMasterRecord(symbol="MRVL", name="Marvell Technology Inc.", asset_type="stock", exchange="NASDAQ", sector="Technology"),
    SecurityMasterRecord(symbol="ORCL", name="Oracle Corporation", asset_type="stock", exchange="NYSE", sector="Technology"),
    SecurityMasterRecord(symbol="IBM", name="International Business Machines", asset_type="stock", exchange="NYSE", sector="Technology"),
    SecurityMasterRecord(symbol="LMT", name="Lockheed Martin Corporation", asset_type="stock", exchange="NYSE", sector="Industrials"),
    SecurityMasterRecord(symbol="GE", name="GE Aerospace", asset_type="stock", exchange="NYSE", sector="Industrials"),
    SecurityMasterRecord(symbol="HON", name="Honeywell International Inc.", asset_type="stock", exchange="NASDAQ", sector="Industrials"),
    SecurityMasterRecord(symbol="MMM", name="3M Company", asset_type="stock", exchange="NYSE", sector="Industrials"),
    SecurityMasterRecord(symbol="NKE", name="NIKE Inc.", asset_type="stock", exchange="NYSE", sector="Consumer Cyclical"),
    SecurityMasterRecord(symbol="LULU", name="Lululemon Athletica Inc.", asset_type="stock", exchange="NASDAQ", sector="Consumer Cyclical"),
]
